language: node_js

node_js:
  - "0.10"

# whitelist
branches:
only:
  - dev

env:
  global:
    - GH_REF: github.com/antouank/interpreter.git
    # GH_TOKEN
    - secure: 38f3a0d7b719e5f8e388d10cff7b7449ded4e1f5
